include:
  - project: 'templates/gitlab-ci'
    ref: '3.0.1'
    file: 'autodevops/gitlab-ci.yml'
  - project: 'templates/gitlab-ci'
    ref: '3.0.1'
    file: 'autodevops/jobs/version.yml'

build:
  stage: build
  image: docker:18.09.6-git
  variables:
    DOCKER_HOST: tcp://docker:2375
  services:
    - docker:18.09.7-dind
  script:
    - |
      echo "Logging to Quay Container Registry with CI credentials..."
      docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD" "$DOCKER_REGISTRY"
      use_version
      docker build -t $DOCKER_REGISTRY/glennole/homeassistant.service:$CI_APPLICATION_TAG -t $DOCKER_REGISTRY/glennole/homeassistant.service:latest .
      docker push $DOCKER_REGISTRY/glennole/homeassistant.service:$CI_APPLICATION_TAG
      docker push $DOCKER_REGISTRY/glennole/homeassistant.service:latest
  only:
    - branches
.auto_devops: &auto_devops |
  # Auto DevOps variables and functions
  [[ "$TRACE" ]] && set -x
  if [[ -z "$CI_COMMIT_TAG" ]]; then
    export CI_APPLICATION_REPOSITORY=$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG
    export CI_APPLICATION_TAG=$CI_COMMIT_SHA
  else
    export CI_APPLICATION_REPOSITORY=$CI_REGISTRY_IMAGE
    export CI_APPLICATION_TAG=$CI_COMMIT_TAG
  fi

  use_version() {
      tag=$(cat ./version.txt)
      if [[ -n "$tag" ]]; then
        export CI_APPLICATION_TAG=${tag:-$CI_APPLICATION_TAG}
      fi
  }

before_script:
  - *auto_devops
